from app.llm.prompts.requirement import REQUIREMENT_SYSTEM_PROMPT, REQUIREMENT_EXTRACTION_TEMPLATE
from app.llm.prompts.rag import RAG_SYSTEM_PROMPT, RAG_CONTEXT_TEMPLATE
from app.llm.prompts.writer import WRITER_SYSTEM_PROMPT, PROPOSAL_WRITER_TEMPLATE
from app.llm.prompts.reviewer import REVIEWER_SYSTEM_PROMPT, PROPOSAL_REVIEWER_TEMPLATE

__all__ = [
    "REQUIREMENT_SYSTEM_PROMPT",
    "REQUIREMENT_EXTRACTION_TEMPLATE",
    "RAG_SYSTEM_PROMPT",
    "RAG_CONTEXT_TEMPLATE",
    "WRITER_SYSTEM_PROMPT",
    "PROPOSAL_WRITER_TEMPLATE",
    "REVIEWER_SYSTEM_PROMPT",
    "PROPOSAL_REVIEWER_TEMPLATE",
]
