from app.llm.prompts.requirement import REQUIREMENT_SYSTEM_PROMPT, REQUIREMENT_EXTRACTION_TEMPLATE
from app.llm.prompts.rag import RAG_SYSTEM_PROMPT, RAG_CONTEXT_TEMPLATE
from app.llm.prompts.writer import WRITER_SYSTEM_PROMPT, PROPOSAL_WRITER_TEMPLATE
from app.llm.prompts.reviewer import REVIEWER_SYSTEM_PROMPT, PROPOSAL_REVIEWER_TEMPLATE
from app.llm.prompts.module import MODULE_SYSTEM_PROMPT, MODULE_EXTRACTION_TEMPLATE
from app.llm.prompts.compliance import COMPLIANCE_SYSTEM_PROMPT, COMPLIANCE_EXTRACTION_TEMPLATE
from app.llm.prompts.tech_stack import STACK_RATIONALE_SYSTEM_PROMPT, STACK_RATIONALE_TEMPLATE

__all__ = [
    "REQUIREMENT_SYSTEM_PROMPT",
    "REQUIREMENT_EXTRACTION_TEMPLATE",
    "RAG_SYSTEM_PROMPT",
    "RAG_CONTEXT_TEMPLATE",
    "WRITER_SYSTEM_PROMPT",
    "PROPOSAL_WRITER_TEMPLATE",
    "REVIEWER_SYSTEM_PROMPT",
    "PROPOSAL_REVIEWER_TEMPLATE",
    "MODULE_SYSTEM_PROMPT",
    "MODULE_EXTRACTION_TEMPLATE",
    "COMPLIANCE_SYSTEM_PROMPT",
    "COMPLIANCE_EXTRACTION_TEMPLATE",
    "STACK_RATIONALE_SYSTEM_PROMPT",
    "STACK_RATIONALE_TEMPLATE",
]
