from app.engines.base_engine import BaseEngine

INDUSTRY_PATTERNS = {
    "healthcare": {
        "label": "Healthcare",
        "compliance": ["HIPAA", "HITECH", "GDPR"],
        "standards": ["HL7 FHIR", "DICOM", "ICD-10"],
        "concerns": ["patient_data_privacy", "regulatory_compliance", "interoperability"],
        "trends": ["telemedicine", "ehr", "ai_diagnostics", "patient_portal"],
        "stakeholders": ["patients", "doctors", "admin_staff", " insurers"],
        "complexity": "high",
    },
    "erp": {
        "label": "Enterprise ERP",
        "compliance": ["SOX", "GAAP", "IFRS"],
        "standards": ["ISO 9001", "ISA-95"],
        "concerns": ["data_migration", "system_integration", "business_continuity"],
        "trends": ["cloud_erp", "ai_planning", "iot_integration", "automation"],
        "stakeholders": ["cfo", "operations", "supply_chain", "it"],
        "complexity": "high",
    },
    "crm": {
        "label": "CRM",
        "compliance": ["GDPR", "CCPA", "CAN-SPAM"],
        "standards": [],
        "concerns": ["data_quality", "user_adoption", "integration_existing"],
        "trends": ["ai_sales", "conversational_crm", "predictive_analytics"],
        "stakeholders": ["sales", "marketing", "support", "management"],
        "complexity": "medium",
    },
    "hrms": {
        "label": "HRMS",
        "compliance": ["EEOC", "FLSA", "GDPR", "SOC 2"],
        "standards": ["HR-XML"],
        "concerns": ["payroll_accuracy", "benefit_admin", "employee_experience"],
        "trends": ["people_analytics", "remote_work", "ai_recruiting", "self_service"],
        "stakeholders": ["hr", "payroll", "employees", "management"],
        "complexity": "medium",
    },
    "manufacturing": {
        "label": "Manufacturing ERP",
        "compliance": ["ISO 9001", "ISO 14001", "OSHA"],
        "standards": ["ISA-95", "MESA", "OPC-UA"],
        "concerns": ["production_scheduling", "quality_control", "inventory", "supply_chain"],
        "trends": ["industry_4_0", "digital_twin", "predictive_maintenance", "iot"],
        "stakeholders": ["production", "quality", "logistics", "plant_manager"],
        "complexity": "high",
    },
    "education": {
        "label": "Education",
        "compliance": ["FERPA", "COPPA", "ADA"],
        "standards": ["SCORM", "xAPI", "LTI"],
        "concerns": ["student_privacy", "accessibility", "engagement"],
        "trends": ["adaptive_learning", "lms", "virtual_classrooms", "micro_credentials"],
        "stakeholders": ["students", "teachers", "admin", "parents"],
        "complexity": "medium",
    },
    "government": {
        "label": "Government",
        "compliance": ["FedRAMP", "NIST 800-53", "SOC 2", "ITAR"],
        "standards": ["FIPS", "GSA"],
        "concerns": ["security_clearance", "audit_trail", "data_sovereignty"],
        "trends": ["digital_government", "open_data", "smart_cities"],
        "stakeholders": ["agencies", "citizens", "contractors", "auditors"],
        "complexity": "very_high",
    },
    "retail": {
        "label": "Retail",
        "compliance": ["PCI DSS", "GDPR"],
        "standards": ["GS1", "EDI"],
        "concerns": ["omni_channel", "inventory", "customer_experience", "fraud"],
        "trends": ["ecommerce", "personalization", "pos", "loyalty_ai"],
        "stakeholders": ["customers", "merchants", "supply_chain", "marketing"],
        "complexity": "medium",
    },
    "logistics": {
        "label": "Logistics",
        "compliance": ["DOT", "FMCSA", "Customs"],
        "standards": ["EDI 204/214", "GS1"],
        "concerns": ["route_optimization", "real_time_tracking", "fleet_management"],
        "trends": ["last_mile_delivery", "warehouse_automation", "blockchain"],
        "stakeholders": ["dispatchers", "drivers", "customers", "warehouse"],
        "complexity": "medium",
    },
    "construction": {
        "label": "Construction",
        "compliance": ["OSHA", "BIM", "LEED"],
        "standards": ["IFC", "COBie"],
        "concerns": ["project_delays", "cost_overruns", "safety_compliance"],
        "trends": ["bim", "drone_survey", "digital_twin", "prefab"],
        "stakeholders": ["contractors", "architects", "engineers", "owners"],
        "complexity": "high",
    },
    "finance": {
        "label": "Finance & Banking",
        "compliance": ["SOX", "PCI DSS", "KYC", "AML", "Basel III"],
        "standards": ["ISO 20022", "SWIFT", "FIX"],
        "concerns": ["security", "regulatory", "fraud_detection", "data_privacy"],
        "trends": ["fintech", "open_banking", "blockchain", "ai_trading"],
        "stakeholders": ["customers", "regulators", "traders", "compliance"],
        "complexity": "very_high",
    },
}

INDUSTRY_ALIASES = {
    "health": "healthcare",
    "medical": "healthcare",
    "hospital": "healthcare",
    "finance": "finance",
    "banking": "finance",
    "insurance": "finance",
    "bank": "finance",
    "school": "education",
    "university": "education",
    "college": "education",
    "training": "education",
    "government": "government",
    "public_sector": "government",
    "retail": "retail",
    "ecommerce": "retail",
    "shop": "retail",
    "logistics": "logistics",
    "transportation": "logistics",
    "shipping": "logistics",
    "construction": "construction",
    "real_estate": "construction",
    "infrastructure": "construction",
    "manufacturing": "manufacturing",
    "factory": "manufacturing",
    "production": "manufacturing",
    "erp": "erp",
    "enterprise": "erp",
    "crm": "crm",
    "sales": "crm",
    "hrms": "hrms",
    "human_resources": "hrms",
    "payroll": "hrms",
    "ai": "custom",
    "saas": "custom",
    "software": "custom",
    "mobile": "custom",
    "web": "custom",
}


class IndustryEngine(BaseEngine):
    name = "industry"

    def run(self, context: dict) -> dict:
        domain = (context.get("domain") or context.get("industry") or "custom").lower().strip()
        resolved = INDUSTRY_ALIASES.get(domain)
        if not resolved:
            resolved = "custom" if domain not in INDUSTRY_PATTERNS else domain
        pattern = INDUSTRY_PATTERNS.get(resolved, INDUSTRY_PATTERNS.get("custom", {
            "label": "Custom Software",
            "compliance": [],
            "standards": [],
            "concerns": ["requirements_clarity", "timeline_accuracy", "quality_assurance"],
            "trends": ["cloud_native", "microservices", "agile", "devops"],
            "stakeholders": ["product_owners", "developers", "users", "management"],
            "complexity": "medium",
        }))
        return {
            "industry": resolved,
            "pattern": pattern,
            "compliance_requirements": pattern["compliance"],
            "applicable_standards": pattern["standards"],
            "key_concerns": pattern["concerns"],
            "industry_trends": pattern["trends"],
            "stakeholders": pattern["stakeholders"],
            "complexity": pattern["complexity"],
        }
